site_name: mantis-delta
site_url: https://emiliovenegas.github.io/mantis-delta
repo_url: https://github.com/emiliovenegas/mantis-delta
repo_name: emiliovenegas/mantis-delta

theme:
  name: material
  palette:
    primary: indigo
    accent: deep purple
  features:
    - navigation.sections
    - navigation.top

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

nav:
  - Home: index.md
  - API Reference: api.md
